model:
  class_path: aio4_bpr_baseline.retriever.bpr.lightning_modules.BPREmbedderLightningModule
trainer:
  devices: 4
  precision: 16-mixed
  callbacks:
    - class_path: aio4_bpr_baseline.callbacks.prediction_writer.NumpyPredictionWriter
seed_everything: 0
