model:
  class_path: aio4_bpr_baseline.reader.extractive_reader.lightning_modules.ExtractiveReaderPredictLightningModule
trainer:
  devices: 4
  precision: 16-mixed
  callbacks:
    - class_path: aio4_bpr_baseline.callbacks.prediction_writer.JsonPredictionWriter
seed_everything: 0
