model:
  class_path: aio4_bpr_baseline.reader.extractive_reader.lightning_modules.ExtractiveReaderLightningModule
  init_args:
    base_model_name: cl-tohoku/bert-base-japanese-v3
trainer:
  devices: 4
  precision: 16-mixed
  max_epochs: 10
  accumulate_grad_batches: 4
  gradient_clip_val: 2.0
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: best
        monitor: val_joint_accuracy
        save_last: true
        mode: max
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
seed_everything: 0
