model:
  class_path: models.retriever.Retriever
  init_args:
    base_model_name: cl-tohoku/bert-base-japanese-v3
trainer:
  devices: 4
  precision: 16-mixed
  max_epochs: 40
  gradient_clip_val: 2.0
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        filename: best
        monitor: val_average_rank
        save_last: true
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: callbacks.prediction_writer.JsonPredictionWriter
seed_everything: 0
