model:
  class_path: aio4_bpr_baseline.pipeline_aio4.bpr_extractive_reader.lightning_modules.BPRExtractiveReaderPipelineLightningModule
trainer:
  devices: 4
  precision: 16-mixed
  callbacks:
    - class_path: aio4_bpr_baseline.callbacks.prediction_writer.JsonPredictionWriter
seed_everything: 0
